app:
    name: product
    grpc:
        port: 9090
        host: localhost
    port: 8080

db:
    host: localhost
    port: 5432
    user: admin
    pass: admin
    name: db

redis:
    addr: "localhost:6379"
    pass: ""
    db: 0
